apiVersion: v1
kind: Service
metadata:
  name: ingress-request-dumper
  labels:
    app.kubernetes.io/name: ingress-request-dumper
    app.kubernetes.io/created-by: ssbostan
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ingress-request-dumper
    app.kubernetes.io/created-by: ssbostan
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-request-dumper
  labels:
    app.kubernetes.io/name: ingress-request-dumper
    app.kubernetes.io/created-by: ssbostan
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-request-dumper
      app.kubernetes.io/created-by: ssbostan
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-request-dumper
        app.kubernetes.io/created-by: ssbostan
    spec:
      restartPolicy: Always
      automountServiceAccountToken: false
      containers:
        - name: ingress-request-dumper
          image: ssbostan/ingress-request-dumper:latest
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 20m
              memory: 20Mi
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            tcpSocket:
              port: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /readyz
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
